import { Website, WebsiteSection } from './types';

// Placeholder service to simulate Gemini API calls

export const generateWebsite = async (niche: string, description: string): Promise<Website> => {
  console.log(`Generating website for niche: ${niche}, description: ${description}`);
  // In a real app, this would call the Gemini API
  await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate network delay
  
  return {
    id: 'site_' + Date.now(),
    name: description.split(':')[0] || 'New AI Site',
    niche: niche,
    themeColor: '#4f46e5', // indigo-600 from tailwind.config.js
    sections: [
      { id: 'sec_1', type: 'hero', content: { title: 'Welcome to ' + (description.split(':')[0] || 'New AI Site'), text: 'This is a hero section generated by AI.' } },
      { id: 'sec_2', type: 'features', content: { title: 'Our Features', items: [{title: 'Feature 1', text: 'Description 1'}, {title: 'Feature 2', text: 'Description 2'}] } },
    ],
  };
};

export const regenerateSection = async (section: WebsiteSection, prompt: string): Promise<WebsiteSection> => {
  console.log(`Regenerating section ${section.id} with prompt: ${prompt}`);
  // In a real app, this would call the Gemini API
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    ...section,
    content: {
      ...section.content,
      title: (section.content.title || '') + ' (Updated)',
      text: `Updated based on prompt: "${prompt}"`,
    }
  };
};